version: '3.7'
services:
  postgres:
    image: postgres:latest
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=9mRE